FROM golang:1.17 as build_api
ENV CGO_ENABLED 0
ARG BUILD_REF


COPY . /service
WORKDIR /service

RUN go build -o service -ldflags "-X main.build={$BUILD_REF}"


FROM alpine:3.15
COPY --from=build_api service /service
WORKDIR /service
CMD ["./service"]